import { User } from "../core/_model";

export const dataSource: User[] = [
  {
    id: 1,
    gender: "Male",
    email: "john.doe@example.com",
    firstname: "John",
    middlename: "Michael",
    lastname: "Doe",
    birthdate: "1990-05-15",
    birthplace: "New York, USA",
    citizenship: "American",
  },
  {
    id: 2,
    gender: "Female",
    email: "jane.smith@example.com",
    firstname: "Jane",
    middlename: "Elizabeth",
    lastname: "Smith",
    birthdate: "1995-08-22",
    birthplace: "Los Angeles, USA",
    citizenship: "American",
  },
  {
    id: 3,
    gender: "Male",
    email: "david.nguyen@example.com",
    firstname: "David",
    middlename: "Hoang",
    lastname: "Nguyen",
    birthdate: "1988-12-10",
    birthplace: "Ho Chi Minh City, Vietnam",
    citizenship: "Vietnamese",
  },
  {
    id: 4,
    gender: "Female",
    email: "emily.johnson@example.com",
    firstname: "Emily",
    middlename: "Grace",
    lastname: "Johnson",
    birthdate: "1992-04-30",
    birthplace: "Toronto, Canada",
    citizenship: "Canadian",
  },
  {
    id: 5,
    gender: "Male",
    email: "mohamed.ali@example.com",
    firstname: "Mohamed",
    middlename: "Ahmed",
    lastname: "Ali",
    birthdate: "1985-06-18",
    birthplace: "Cairo, Egypt",
    citizenship: "Egyptian",
  },
  {
    id: 6,
    gender: "Female",
    email: "sophia.garcia@example.com",
    firstname: "Sophia",
    middlename: "Isabel",
    lastname: "Garcia",
    birthdate: "1998-03-12",
    birthplace: "Madrid, Spain",
    citizenship: "Spanish",
  },
  {
    id: 7,
    gender: "Male",
    email: "ryan.kim@example.com",
    firstname: "Ryan",
    middlename: "Joon",
    lastname: "Kim",
    birthdate: "1993-09-25",
    birthplace: "Seoul, South Korea",
    citizenship: "South Korean",
  },
  {
    id: 8,
    gender: "Female",
    email: "hannah.wilson@example.com",
    firstname: "Hannah",
    middlename: "Rose",
    lastname: "Wilson",
    birthdate: "2000-01-17",
    birthplace: "Sydney, Australia",
    citizenship: "Australian",
  },
  {
    id: 9,
    gender: "Male",
    email: "luca.rossi@example.com",
    firstname: "Luca",
    middlename: "Antonio",
    lastname: "Rossi",
    birthdate: "1987-07-08",
    birthplace: "Rome, Italy",
    citizenship: "Italian",
  },
  {
    id: 10,
    gender: "Female",
    email: "natalia.kovalenko@example.com",
    firstname: "Natalia",
    middlename: "Viktorovna",
    lastname: "Kovalenko",
    birthdate: "1996-11-03",
    birthplace: "Kyiv, Ukraine",
    citizenship: "Ukrainian",
  },
  {
    id: 11,
    gender: "Male",
    email: "oliver.tanaka@example.com",
    firstname: "Oliver",
    middlename: "Haruto",
    lastname: "Tanaka",
    birthdate: "1994-05-21",
    birthplace: "Tokyo, Japan",
    citizenship: "Japanese",
  },
  {
    id: 12,
    gender: "Female",
    email: "amelie.dupont@example.com",
    firstname: "Amelie",
    middlename: "Claire",
    lastname: "Dupont",
    birthdate: "1989-12-14",
    birthplace: "Paris, France",
    citizenship: "French",
  },
  {
    id: 13,
    gender: "Male",
    email: "carlos.mendoza@example.com",
    firstname: "Carlos",
    middlename: "Andrés",
    lastname: "Mendoza",
    birthdate: "1983-06-30",
    birthplace: "Buenos Aires, Argentina",
    citizenship: "Argentinian",
  },
  {
    id: 14,
    gender: "Female",
    email: "fatima.hassan@example.com",
    firstname: "Fatima",
    middlename: "Aisha",
    lastname: "Hassan",
    birthdate: "1991-02-28",
    birthplace: "Dubai, UAE",
    citizenship: "Emirati",
  },
  {
    id: 15,
    gender: "Male",
    email: "ethan.park@example.com",
    firstname: "Ethan",
    middlename: "Min",
    lastname: "Park",
    birthdate: "1997-08-09",
    birthplace: "Seoul, South Korea",
    citizenship: "South Korean",
  },
];
