grpc:
  server:
    port: 9120
spring:
  profiles:
    active: dev # Activate the 'dev' profile for discovery-service
  config:
    # import: optional:configserver:http://config-server:8888  # Import configuration from Config Server
    import: optional:configserver:http://localhost:8888 # Import configuration from Config Server
  application:
    name: order-service
  output:
    ansi:
      enabled: always
  reactor:
    context-propagation: AUTO
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
    producer:
      bootstrap-servers: localhost:9092
logging:
  level:
    org.apache.kafka.clients.producer.ProducerConfig: WARN
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health, info
grpc-server:
  user:
    service:
      address: "localhost:9090"
  customer:
    service:
      address: "localhost:9110"
  product:
    service:
      address: "localhost:9130"
  payment:
    service:
      address: "localhost:9140"
