grpc:
  server:
    port: 9110
spring:
  profiles:
    active: dev # Activate the 'dev' profile for discovery-service
  config:
    # import: optional:configserver:http://config-server:8888  # Import configuration from Config Server
    import: optional:configserver:http://localhost:8888 # Import configuration from Config Server
  application:
    name: customer-service
  output:
    ansi:
      enabled: always
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health, info
