server:
  port: 8888
spring:
  profiles:
    active: dev
  application:
    name: config-server
  cloud:
    config:
      profile: dev
      server:
        # native:
        #   search-locations: classpath:/configurations
        git:
          uri: https://github.com/ptho1504/git-config-repo
          default-label: local
          searchPaths: discovery-service, customer-service, gateway-service, user-service, auth-service, product-service, order-service, notify-service, payment-service, upload-service # TODO add some service in heare bro
          # cloneOnStart: true
  output:
    ansi:
      enabled: always
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
