grpc:
  server:
    port: 9000
  security:
    auth:
      enabled: false
spring:
  profiles:
    active: dev # Activate the 'dev' profile for discovery-service
  config:
    import: configserver:http://config-server:8888 # Import configuration from Config Server
  application:
    name: auth-service
  output:
    ansi:
      enabled: always

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

application:
  jwt:
    secretkey: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"
    expiration-time: 36000000
grpc-server:
  user:
    service:
      address: "user-server:9090"
  customer:
    service:
      address: "customer-server:9110"
