grpc:
  server:
    port: 9140
spring:
  profiles:
    active: dev # Activate the 'dev' profile for discovery-service
  config:
    # import: optional:configserver:http://config-server:8888  # Import configuration from Config Server
    import: optional:configserver:http://localhost:8888 # Import configuration from Config Server
  application:
    name: payment-service
  output:
    ansi:
      enabled: always
      spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
    producer:
      bootstrap-servers: localhost:9092
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health, info
payos:
  clientId: 
  apiKey: 
  checkSumKey: 
  webhookUrl: https://dbaf-104-28-237-71.ngrok-free.app/api/v1/payments/pay-os/handle-web-hook
  returnUrl: https://dbaf-104-28-237-71.ngrok-free.app/api/v1/payments/success
  cancelUrl: https://dbaf-104-28-237-71.ngrok-free.app/api/v1/payments/cancel
